# Generated by Django 3.2.7 on 2021-12-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinhocompra',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='listadesejo',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
