# Generated by Django 3.2.7 on 2021-10-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_carrinhocompras_carrinhocompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinhocompra',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
