# Generated by Django 3.2.7 on 2021-10-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_listadesejo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
