# Generated by Django 3.2.7 on 2021-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhocompra',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
