# Generated by Django 3.2.7 on 2021-11-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_pedido_pedidoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(),
        ),
    ]
