# Generated by Django 3.2.7 on 2021-11-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_auto_20211107_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_forma_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.formapagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_transportadora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.transportadora'),
        ),
    ]
