# Generated by Django 3.2.7 on 2021-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_auto_20211107_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=100),
        ),
    ]
