# Generated by Django 3.2.7 on 2021-11-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_produto_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_transportadora',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='id_produto',
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProduto',
        ),
        migrations.DeleteModel(
            name='Transportadora',
        ),
    ]
