# Generated by Django 3.2.7 on 2021-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_auto_20211117_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarrinhoCompra',
        ),
    ]
