# Generated by Django 3.2.7 on 2021-11-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_delete_carrinhocompra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaDesejo',
        ),
    ]
