# Generated by Django 3.2.7 on 2021-11-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_delete_listadesejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendas',
            field=models.IntegerField(default=0),
        ),
    ]
