# Generated by Django 3.2.7 on 2021-12-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_forma_pagamento',
            new_name='forma_pagamento',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_transportadora',
            new_name='transportadora',
        ),
        migrations.RenameField(
            model_name='pedidoproduto',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='pedidoproduto',
            old_name='id_produto',
            new_name='produto',
        ),
    ]
